### ISSUE TITLE
naming

### ISSUE THREAD

**Issue by Admirallll** [arslan174/Calculator#3]
https://github.com/arslan174/Calculator/blob/ad94ffc1e4f0e937ad436a5e0cf2758acc0e94d6/ConsoleApp6/Program.cs#L8
console*

**Comment by Admirallll** [comment]
+ переименовать папку с проектом, она всё ещё по старому называется

**Comment by ars-ish** [comment]
https://github.com/arslan174/Calculator/pull/4
